openapi: 3.1.0
info:
  title: API сервер для учебного проекта "Six sities".
  description: |-
    * Список ресурсов и маршрутов сервера "Six sities".
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 2.0.0
