openapi: 3.1.0
info:
  title: API сервер для учебного проекта "Six sities".
  description: |-
    * Список ресурсов и маршрутов сервера "Six sities".
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 2.0.0
tags:
  - name: offers
    description: Действия с объявлениями.
  - name: comments
    description: Действия с комментариями.
  - name: users
    description: Действия с пользователем.

paths:
  /users/register:
    post:
      tags:
       - users
      summary: Регистрация пользователя
      description: Регистрирует нового пользователя.

      requestBody:
        description: Информация для создания нового пользователя.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createUser'
        required: true

      responses:
        "201":
          description: Пользователь зарегистрирован. Объект пользователя.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'

        "409":
          description: Пользователь с таким email уже существует.

  /users/login:
    post:
      tags:
        - users
      summary: Авторизация пользователя
      description: Авторизирует пользователя на основе логина и пароля

    get:
      tags:
        - users
      summary: Проверка состояния пользователя
      description: Возвращает информацию по авторизованному пользователю

  /users/{userId}/avatar:
    post:
      tags:
        - users
      summary: Загрузить изображение аватара
      description: Загружает изображение аватара пользователя. Изображение аватара
        должно быть в формате `png` или `jpg`.

components:
  schemas:
    createUer:
      type: object

      properties:
        name:
          type: string
          example: Harry Kane

        email:
          type: string
          example: keks@htmlacademy.ru

        password:
          type: string
          example: 123456

    type: object

    properties:
      id:
        type: string
        example: 6329c3d6a04ab1061c6425ea

      email:
        type: string
        example: keks@htmlacademy.ru
