# Комментарии
## Добавить комментарий к офферу по id оффера
POST http://localhost:4000/comments/654871a654427e61077adeba HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiSGFycnkgS2FuZSIsImVtYWlsIjoia2FuZUBnbWFpbC5ydSIsImlkIjoiNjU0ODcxZDRlZjI2MTkzZWNkNWYyMGI0IiwiaWF0IjoxNjk5MjgzOTIyLCJleHAiOjE2OTk0NTY3MjJ9.eSXVOQQXc1IlHWXTyxkZgkdev7U03KEEg4vplLalwhM

{
  "text": "ЕЩЕ ОДИН комментарий от HarryKane с рейтингом равным 5",
  "rating": 5
}
###

## Получить список комментариев к офферу по id оффера
GET http://localhost:4000/comments/654871a654427e61077adeba HTTP/1.1
###
